# -*- coding: utf-8 -*-
"""upi_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ldrk8zZM-LrK85UgEAjIiJBSGbUuXcVS
"""

import pandas as pd
import numpy as np

df=pd.read_excel("/content/upi_transactions_raw.xlsx",sheet_name="upi_data")
df.head()

df.info()

print("Dataset shape:")
print(df.shape)

print("\n-----------------------------")
print("Column names:")
print(df.columns.tolist())

print("Data types:")
df.dtypes

print("\nMissing values in each column:\n")
print(df.isnull().sum())

# Step 5: Sort dataset by Month_Start_Date
df = df.sort_values("Month_Start_Date").reset_index(drop=True)

print(df.head())

print("Last 5 rows after sorting:\n")
print(df.tail())

"""Month-on-Month growth

"""

df["MoM_Volume_Growth_%"] = (df["UPI_Volume_Mn"].pct_change() * 100).round(2)
df["MoM_Value_Growth_%"] = (df["UPI_Value_Cr"].pct_change() * 100).round(2)

print(df[[
    "Month",
    "UPI_Volume_Mn",
    "UPI_Value_Cr",
    "MoM_Volume_Growth_%",
    "MoM_Value_Growth_%"
]].head(10))

"""Year-on-Year growth"""

df["YoY_Volume_Growth_%"] = (df["UPI_Volume_Mn"].pct_change(periods=12) * 100).round(2)
df["YoY_Value_Growth_%"] = (df["UPI_Value_Cr"].pct_change(periods=12) * 100).round(2)

print(df[[
    "Month",
    "UPI_Volume_Mn",
    "UPI_Value_Cr",
    "MoM_Volume_Growth_%",
    "MoM_Value_Growth_%",
    "YoY_Volume_Growth_%",
    "YoY_Value_Growth_%"
]].head(15))

df["Month_Name"] = df["Month_Start_Date"].dt.strftime("%B")
df["Calendar_Quarter"] = df["Month_Start_Date"].dt.quarter

print(df.head())

df.columns.tolist()

df.to_csv("upi_transactions.csv", index=False)

print("File exported successfully ")

"""yearly summary table

"""

yearly_summary = df.groupby("Financial_Year").agg({
    "UPI_Volume_Mn": "sum",
    "UPI_Value_Cr": "sum",
    "Banks_Live": "mean",
    "Avg_Transaction_Value": "mean",
    "MoM_Volume_Growth_%": "mean",
    "MoM_Value_Growth_%": "mean"
}).reset_index().round(2)

yearly_summary.columns = [
    "Financial_Year",
    "Total_UPI_Volume_Mn",
    "Total_UPI_Value_Cr",
    "Avg_Banks_Live",
    "Avg_Transaction_Value",
    "Avg_MoM_Volume_Growth_%",
    "Avg_MoM_Value_Growth_%"
]
yearly_summary

"""quarterly summary table





"""

quarterly_summary = df.groupby(["Financial_Year", "Quarter"]).agg({
    "UPI_Volume_Mn": "sum",
    "UPI_Value_Cr": "sum",
    "Banks_Live": "mean",
    "Avg_Transaction_Value": "mean",
    "MoM_Volume_Growth_%": "mean",
    "MoM_Value_Growth_%": "mean"
}).reset_index().round(2)

quarterly_summary.columns = [
    "Financial_Year",
    "Quarter",
    "Total_UPI_Volume_Mn",
    "Total_UPI_Value_Cr",
    "Avg_Banks_Live",
    "Avg_Transaction_Value",
    "Avg_MoM_Volume_Growth_%",
    "Avg_MoM_Value_Growth_%"
]
quarterly_summary.head()

"""Top 5 months by UPI Volume and Value"""

top_volume_months = df[[
    "Month",
    "Financial_Year",
    "UPI_Volume_Mn",
    "UPI_Value_Cr",
    "Banks_Live"
]].sort_values("UPI_Volume_Mn", ascending=False).head(5)
top_volume_months

top_value_months = df[[
    "Month",
    "Financial_Year",
    "UPI_Volume_Mn",
    "UPI_Value_Cr",
    "Banks_Live"
]].sort_values("UPI_Value_Cr", ascending=False).head(5)
top_value_months

"""Top 5 months by MoM Volume Growth %

"""

top_mom_volume_growth = df[[
    "Month",
    "Financial_Year",
    "UPI_Volume_Mn",
    "MoM_Volume_Growth_%"
]].sort_values("MoM_Volume_Growth_%", ascending=False).head(5)
top_mom_volume_growth

"""Top 5 months by MoM Value Growth %"""

top_mom_value_growth = df[[
    "Month",
    "Financial_Year",
    "UPI_Value_Cr",
    "MoM_Value_Growth_%"
]].sort_values("MoM_Value_Growth_%", ascending=False).head(5)
top_mom_value_growth

"""Top 5 months by YoY Volume Growth %"""

top_yoy_volume_growth = df[[
    "Month",
    "Financial_Year",
    "UPI_Volume_Mn",
    "YoY_Volume_Growth_%"
]].sort_values("YoY_Volume_Growth_%", ascending=False).head(5)
top_yoy_volume_growth

"""Top 5 months by YoY Value Growth %"""

top_yoy_value_growth = df[[
    "Month",
    "Financial_Year",
    "UPI_Value_Cr",
    "YoY_Value_Growth_%"
]].sort_values("YoY_Value_Growth_%", ascending=False).head(5)
top_yoy_value_growth

df.to_csv("upi_transactions.csv", index=False)

print("File exported successfully ")